../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 545 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 546 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 547 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 548 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 549 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 550 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 551 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 552 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 553 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 554 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 555 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 556 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 557 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 558 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 559 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 560 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 561 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 562 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 563 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 564 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 565 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 566 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 567 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 568 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 569 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 570 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 571 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 572 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 573 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 574 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 575 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 576 --validation false
