../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 609 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 610 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 611 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 612 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 613 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 614 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 615 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 616 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 617 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 618 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 619 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 620 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 621 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 622 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 623 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 624 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 625 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 626 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 627 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 628 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 629 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 630 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 631 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 632 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 633 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 634 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 635 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 636 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 637 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 638 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 639 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_eca_rs.txt --seed 640 --validation false
