../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 97 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 98 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 99 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 100 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 101 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 102 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 103 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 104 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 105 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 106 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 107 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 108 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 109 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 110 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 111 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 112 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 113 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 114 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 115 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 116 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 117 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 118 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 119 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 120 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 121 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 122 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 123 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 124 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 125 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 126 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 127 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 128 --validation false
