../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 129 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 130 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 131 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 132 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 133 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 134 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 135 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 136 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 137 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 138 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 139 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 140 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 141 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 142 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 143 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 144 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 145 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 146 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 147 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 148 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 149 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 150 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 151 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 152 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 153 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 154 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 155 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 156 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 157 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 158 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 159 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_bv_rs.txt --seed 160 --validation false
