../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 1 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 2 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 3 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 4 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 5 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 6 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 7 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 8 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 9 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 10 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 11 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 12 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 13 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 14 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 15 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 16 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 17 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 18 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 19 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 20 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 21 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 22 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 23 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 24 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 25 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 26 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 27 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 28 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 29 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 30 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 31 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_loop_rs.txt --seed 32 --validation false
