../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 225 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 226 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 227 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 228 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 229 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 230 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 231 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 232 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 233 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 234 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 235 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 236 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 237 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 238 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 239 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 240 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 241 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 242 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 243 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 244 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 245 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 246 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 247 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 248 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 249 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 250 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 251 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 252 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 253 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 254 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 255 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 256 --validation false
