../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 385 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 386 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 387 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 388 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 389 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 390 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 391 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 392 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 393 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 394 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 395 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 396 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 397 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 398 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 399 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 400 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 401 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 402 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 403 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 404 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 405 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 406 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 407 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 408 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 409 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 410 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 411 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 412 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 413 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 414 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 415 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_arrays_rs.txt --seed 416 --validation false
