../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 65 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 66 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 67 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 68 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 69 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 70 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 71 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 72 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 73 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 74 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 75 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 76 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 77 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 78 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 79 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 80 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 81 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 82 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 83 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 84 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 85 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 86 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 87 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 88 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 89 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 90 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 91 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 92 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 93 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 94 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 95 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 96 --validation false
