../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 257 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 258 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 259 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 260 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 261 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 262 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 263 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 264 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 265 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 266 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 267 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 268 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 269 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 270 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 271 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 272 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 273 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 274 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 275 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 276 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 277 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 278 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 279 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 280 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 281 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 282 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 283 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 284 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 285 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 286 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 287 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_rs_seq.txt --seed 288 --validation false
