../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 577 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 578 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 579 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 580 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 581 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 582 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 583 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 584 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 585 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 586 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 587 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 588 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 589 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 590 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 591 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 592 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 593 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 594 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 595 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 596 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 597 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 598 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 599 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 600 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 601 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 602 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 603 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 604 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 605 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 606 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 607 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 608 --validation false
