../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 513 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 514 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 515 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 516 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 517 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 518 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 519 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 520 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 521 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 522 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 523 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 524 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 525 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 526 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 527 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 528 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 529 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 530 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 531 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 532 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 533 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 534 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 535 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 536 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 537 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 538 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 539 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 540 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 541 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 542 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 543 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_seq_rs.txt --seed 544 --validation false
