../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 321 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 322 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 323 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 324 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 325 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 326 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 327 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 328 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 329 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 330 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 331 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 332 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 333 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 334 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 335 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 336 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 337 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 338 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 339 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 340 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 341 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 342 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 343 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 344 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 345 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 346 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 347 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 348 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 349 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 350 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 351 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 352 --validation false
