../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 289 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 290 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 291 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 292 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 293 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 294 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 295 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 296 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 297 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 298 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 299 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 300 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 301 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 302 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 303 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 304 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 305 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 306 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 307 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 308 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 309 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 310 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 311 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 312 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 313 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 314 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 315 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 316 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 317 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 318 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 319 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 320 --validation false
