../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 481 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 482 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 483 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 484 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 485 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 486 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 487 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 488 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 489 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 490 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 491 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 492 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 493 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 494 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 495 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 496 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 497 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 498 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 499 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 500 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 501 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 502 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 503 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 504 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 505 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 506 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 507 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 508 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 509 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 510 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 511 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 512 --validation false
