../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 33 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 34 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 35 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 36 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 37 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 38 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 39 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 40 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 41 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 42 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 43 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 44 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 45 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 46 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 47 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 48 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 49 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 50 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 51 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 52 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 53 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 54 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 55 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 56 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 57 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 58 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 59 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 60 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 61 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 62 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 63 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 64 --validation false
