../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 161 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 162 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 163 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 164 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 165 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 166 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 167 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 168 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 169 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 170 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 171 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 172 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 173 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 174 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 175 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 176 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 177 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 178 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 179 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 180 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 181 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 182 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 183 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 184 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 185 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 186 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 187 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 188 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 189 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 190 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 191 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 192 --validation false
