../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 353 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 354 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 355 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 356 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 357 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 358 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 359 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 360 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 361 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 362 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 363 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 364 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 365 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 366 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 367 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 368 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 369 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 370 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 371 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 372 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 373 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 374 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 375 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 376 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 377 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 378 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 379 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 380 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 381 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 382 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 383 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 384 --validation false
