../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 193 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 194 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 195 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 196 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 197 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 198 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 199 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 200 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 201 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 202 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 203 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 204 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 205 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 206 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 207 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 208 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 209 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 210 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 211 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 212 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 213 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 214 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 215 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 216 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 217 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 218 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 219 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 220 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 221 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 222 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 223 --validation false &
../../smac --shared-model-mode true --scenario-file smack-scenario_ldv.txt --seed 224 --validation false
